CREATE TABLE "BL_CL"."LOG_PROCEDURES" (
    "LOG_ID"             BIGINT       PRIMARY KEY,
    "PROCEDURE_NAME"     VARCHAR(255) NOT NULL,
    "TABLE_NAME"         VARCHAR(255) NOT NULL,
    "INSERT_ROW_CNT"     BIGINT       NOT NULL,
    "UPDATE_ROW_CNT"     BIGINT       NOT NULL,
    "TRANSACTION_NUM"    INT          NOT NULL,
    "IS_SUCCESS"         VARCHAR(1)   NOT NULL,
    "EXECITED_TIME_SEC"  FLOAT        NOT NULL,
    "TA_INSERT_DT"       TIMESTAMP    NOT NULL,
    "TA_UPDATE_DT"       TIMESTAMP    NOT NULL
);