CREATE OR REPLACE PROCEDURE "BL_CL"."LOAD_DATA_TO_BL_DM"()
LANGUAGE plpgsql
AS
$$
BEGIN
	
	CALL "BL_CL"."LOAD_DATA_TO_DIM_PAYMENT_TYPES"();
	CALL "BL_CL"."LOAD_DATA_TO_DIM_PLATFORMS"();

	CALL "BL_CL"."LOAD_DATA_TO_DIM_CUSTOMERS"();
	   
	CALL "BL_CL"."LOAD_DATA_TO_DIM_TIME_DAY"();

	CALL "BL_CL"."LOAD_DATA_TO_DIM_PRODUCTS_SCD"();

	ALTER TABLE "BL_DM"."FCT_SALES_DD" DROP CONSTRAINT IF EXISTS fk_dm_sale_date;
	ALTER TABLE "BL_DM"."FCT_SALES_DD" DROP CONSTRAINT IF EXISTS fk_dm_sale_customer;
	ALTER TABLE "BL_DM"."FCT_SALES_DD" DROP CONSTRAINT IF EXISTS fk_dm_sale_product;
	ALTER TABLE "BL_DM"."FCT_SALES_DD" DROP CONSTRAINT IF EXISTS fk_dm_sale_payment_type;
	ALTER TABLE "BL_DM"."FCT_SALES_DD" DROP CONSTRAINT IF EXISTS fk_dm_sale_platform;
	CALL "BL_CL"."LOAD_DATA_TO_FCT_SALES_DD"();
	ALTER TABLE "BL_DM"."FCT_SALES_DD"
	  ADD CONSTRAINT fk_dm_sale_date         FOREIGN KEY ("SALE_DT")              
	                                         REFERENCES "BL_DM"."DIM_TIME_DAY"("DATE_KEY");
	ALTER TABLE "BL_DM"."FCT_SALES_DD"
	  ADD CONSTRAINT fk_dm_sale_customer     FOREIGN KEY ("CUSTOMER_SURR_ID")     
	                                         REFERENCES "BL_DM"."DIM_CUSTOMERS"("CUSTOMER_SURR_ID");
	ALTER TABLE "BL_DM"."FCT_SALES_DD"
	  ADD CONSTRAINT fk_dm_sale_product      FOREIGN KEY ("PRODUCT_SURR_ID")      
	                                         REFERENCES "BL_DM"."DIM_PRODUCTS_SCD"("PRODUCT_SURR_ID");
	ALTER TABLE "BL_DM"."FCT_SALES_DD"
	  ADD CONSTRAINT fk_dm_sale_payment_type FOREIGN KEY ("PAYMENT_TYPE_SURR_ID") 
	                                         REFERENCES "BL_DM"."DIM_PAYMENT_TYPES"("PAYMENT_TYPE_SURR_ID");
	ALTER TABLE "BL_DM"."FCT_SALES_DD"
	  ADD CONSTRAINT fk_dm_sale_platform     FOREIGN KEY ("PLATFORM_SURR_ID") 
	                                         REFERENCES "BL_DM"."DIM_PLATFORMS"("PLATFORM_SURR_ID");
END;
$$;

/*
CALL "BL_CL"."LOAD_DATA_TO_BL_DM"();
 */