CREATE OR REPLACE PROCEDURE "BL_CL".truncate_all_tables_in_BL_DM()
LANGUAGE plpgsql
AS
$$
BEGIN
	
    TRUNCATE TABLE "BL_DM"."DIM_PAYMENT_TYPES" CASCADE;
	TRUNCATE TABLE "BL_DM"."DIM_PLATFORMS"     CASCADE;
	TRUNCATE TABLE "BL_DM"."DIM_CUSTOMERS"     CASCADE;
	TRUNCATE TABLE "BL_DM"."DIM_TIME_DAY"      CASCADE;
	TRUNCATE TABLE "BL_DM"."DIM_PRODUCTS_SCD"  CASCADE;
	TRUNCATE TABLE "BL_DM"."FCT_SALES_DD"      CASCADE;
END;
$$;