-- Create business DIM_TIME_DAY which represents time dimention:
CREATE TABLE IF NOT EXISTS "BL_DM"."DIM_TIME_DAY"(
    "DATE_KEY"               DATE          PRIMARY KEY,
    "DAY_OF_WEEK_NUM"        INT           NOT NULL,
    "DAY_OF_WEEK_DESC"       VARCHAR(255)  NOT NULL,
    "WEEKEND_FLAG"           VARCHAR(1)    NOT NULL,  -- IF WEEKEND THEN '1', ELSE '0'
    "ISO_WEEK_NUM"           INT           NOT NULL,
    "DAY_OF_MONTH_NUM"       INT           NOT NULL,
    "MONTH_VALUE"            VARCHAR(2)    NOT NULL,
    "MONTH_DESC"             VARCHAR(25)   NOT NULL,
    "CALENDAR_QUARTER_VALUE" VARCHAR(1)    NOT NULL,
    "CALENDAR_QUARTER_DESC"  VARCHAR(2)    NOT NULL,
    "CALENDAR_YEAR_VALUE"    VARCHAR(4)    NOT NULL,
    "FISCAL_QUARTER_VALUE"   VARCHAR(1)    NOT NULL,
    "FISCAL_QUARTER_DESC"    VARCHAR(2)    NOT NULL,
    "TA_INSERT_DT"           TIMESTAMP     NOT NULL     DEFAULT CURRENT_TIMESTAMP,
    "TA_UPDATE_DT"           TIMESTAMP     NOT NULL     DEFAULT '9999-12-31 23:59:59'
);