CREATE OR REPLACE PROCEDURE "BL_CL"."LOAD_DATA_TO_BL_3NF"()
LANGUAGE plpgsql
AS
$$
BEGIN

	CALL "BL_CL"."LOAD_DATA_TO_CE_REGIONS"();
	CALL "BL_CL"."LOAD_DATA_TO_CE_SUBREGIONS"();
	CALL "BL_CL"."LOAD_DATA_TO_CE_COUNTRIES"();


	DROP INDEX IF EXISTS  "BL_3NF".btree_ce_bus_customers_id_idx;
	CALL "BL_CL"."LOAD_DATA_TO_CE_CUSTOMERS"();
	CREATE INDEX IF NOT EXISTS btree_ce_bus_customers_id_idx
	    ON "BL_3NF"."CE_CUSTOMERS" ("BUS_CUSTOMER_ID");


	CALL "BL_CL"."LOAD_DATA_TO_CE_PLATFORMS"();
	CALL "BL_CL"."LOAD_DATA_TO_CE_PAYMENT_TYPES"();
	CALL "BL_CL"."LOAD_DATA_TO_CE_PRODUCT_CATEGORIES"();
	CALL "BL_CL"."LOAD_DATA_TO_CE_PRODUCT_SUBCATEGORIES"();

	DROP INDEX IF EXISTS  "BL_3NF".btree_ce_prod_doublet_id_idx;
	CALL "BL_CL"."LOAD_DATA_TO_CE_PRODUCTS_SCD"();
	CREATE INDEX IF NOT EXISTS btree_ce_prod_doublet_id_idx
	    ON "BL_3NF"."CE_PRODUCTS_SCD" ("PRODUCT_CODE", "START_DT");

	CALL "BL_CL"."LOAD_DATA_TO_CE_SALES"();
END;
$$;
