CREATE OR REPLACE PROCEDURE "BL_CL".truncate_temp_tables_in_SA()
LANGUAGE plpgsql
AS
$$
BEGIN
	-- Temp tables 	
	TRUNCATE TABLE "SA_EUROPE_SERVER_SALES"."SRC_EUROPE_SALES" CASCADE;
	TRUNCATE TABLE "SA_GLOBAL_SERVER_SALES"."SRC_GLOBAL_SALES" CASCADE;
END;
$$;