CREATE OR REPLACE PROCEDURE "BL_CL".truncate_arch_tables_in_SA()
LANGUAGE plpgsql
AS
$$
BEGIN
	-- Archive tables. Only super user can delete !!!
	TRUNCATE TABLE "SA_EUROPE_SERVER_SALES"."SRC_EUROPE_SALES_ARCH"  CASCADE;
	TRUNCATE TABLE "SA_GLOBAL_SERVER_SALES"."SRC_GLOBAL_SALES_ARCH"  CASCADE;
END;
$$;