CREATE OR REPLACE PROCEDURE "BL_CL".truncate_all_tables_in_BL_CL()
LANGUAGE plpgsql
AS
$$
BEGIN
	
	TRUNCATE TABLE "BL_CL"."WRK_REGIONS"               CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_SUBREGIONS"            CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_COUNTRIES"             CASCADE;
    TRUNCATE TABLE "BL_CL"."WRK_CUSTOMERS"             CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_PLATFORMS"             CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_PAYMENT_TYPES"         CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_PRODUCT_CATEGORIES"    CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_PRODUCT_SUBCATEGORIES" CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_PRODUCTS_SCD"          CASCADE;
	TRUNCATE TABLE "BL_CL"."WRK_SALES"                 CASCADE;
END;
$$;