/*
CREATE DATABASE "UK_ONLINE_RETAILS_STORE";
 */

CREATE SCHEMA IF NOT EXISTS "SA_EUROPE_SERVER_SALES";

CREATE SCHEMA IF NOT EXISTS "SA_GLOBAL_SERVER_SALES";

CREATE SCHEMA IF NOT EXISTS "BL_CL";

CREATE SCHEMA IF NOT EXISTS "BL_3NF";

CREATE SCHEMA IF NOT EXISTS "BL_DM";